# PostgreSQL — uses Docker service name "postgres"
spring.datasource.url=jdbc:postgresql://postgres:5432/momentum
spring.datasource.username=${DB_USER:momentum_user}
spring.datasource.password=${DB_PASSWORD:Momentum@123}
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway
spring.flyway.user=${DB_USER:momentum_user}
spring.flyway.password=${DB_PASSWORD:Momentum@123}

# JWT
app.jwt.secret=${JWT_SECRET:4d6f6d656e74756d5365637265744b657932303236537472b696e674c6f6e6748617368}

# Swagger disabled in docker
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
